# logging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      hibernate.type.descriptor.sql.BasicBinder: TRACE


# database
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:tmdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  session:
    store-type: jdbc

  # jpa
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8086
