# logging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      hibernate.type.descriptor.sql.BasicBinder: TRACE

# database
spring:
  profiles:
    include: aws
  session:
    store-type: jdbc
  datasource:
    url: ${TM_DB_URL}
    username: ${TM_DB_USERNAME}
    password: ${TM_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

# server
server:
  port: 80
  address: 0.0.0.0
  servlet:
    session:
      timeout: 5h
      cookie:
        http-only: true
        secure: false

# api
your:
  api:
    endpoints:
      - /api